### PR TITLE
Added Starting Scene and text Mesh Pro downloaded

### PR DESCRIPTION
**Pull request by salvolannister**
I added a scene, that we could use as a starting scene where one can change the options for shooting, maybe the gun or the difficulty of the levels.
I thought it could be useful for the future

### CODE REVIEW

**Comment by Ieida** [comment]
The Range scene was meant as a starting scene.

**Comment by salvolannister** [comment]
So wanna keep mine or should we discard? I 'm still working on that right know

**Comment by Ieida** [comment]
Is it the MainMenu scene? Then it's fine to keep.

**Comment by salvolannister** [comment]
I changed the name to MainMenu scene to _PersistentScene. 
I think that the player, the system of canvas and their camera, a minimap ( still to implement) and the audio system should all stay in a persistent scene that loads the different levels.

**Comment by salvolannister** [comment]
I would like the _PersistentScene to have a minimap camera showing the player and the enemies, new canvas for the end and the start of the level, a canvas for the lifes and the score.

**Comment by salvolannister** [comment]
My Idea for the **ZoombieShooter.cs** script is that it should manage the levels of the game and make it advance. 
It should propose different functions that could be called inside other script like "End Game", "Pause Game" etc.., it should also be in charge to keep the state of the game ( pause, play, end, new level, pre level), this state could be useful for different reasons within the game ( as I have shown in the script "ActiveOnlyDuringSomeGameState.cs"

**Pull request merged**
